P4C-3220: add pass for inserting tmp variable before headers flattening (#5980)
This commit adds a new pass called before FlattenHeader pass to inject temporary
variables in following cases:

Extern method returns a structure and this structure is assigned to a nested structure.
Nested structure is passed as an argument to an extern method in a method call statement.
These cases are problematic for FlattenHeader pass as it replaces the structures nested
inside headers by new header fields but the standalone occurrence of this header field
which is a nested structure could not be removed in these cases.
Then it was causing the following error during type checking after FlattenHeader pass:

dead_drop_struct.p4(192): [--Werror=type-error] error: Field box_data is not a member of structure header dead_drop_h
                dead_drop.box_data = pickup_data.execute(dead_drop.box_num);
                          ^^^^^^^^
dead_drop_struct.p4(72)
header dead_drop_h {
       ^^^^^^^^^^^

Using those temporary variables we can avoid this problem.

Also there is added CopyHeaders pass after generating register actions
from read and write methods in RegisterReadWrite pass.
There might be generated structure assignment statements in these register actions
which cause later this bug if they are not replaced by assignments of the fields:

Compiler Bug: Header present in IR not under Member: ingress::tmp_0

This bug was observed on testing program p4-tests/p4_16/compile_only/p4c-3220_2.p4,
therefore this change is also part of this commit.