Regular p4c update (2022-11-21) (#6687)
* Regular p4c update (2022-11-21)

[no-jira]

* Another p4c update

[no-jira]

* Remove from xfails tests moved to error folders

The tests moved to error folders in p4c are now not added to the list
of tests in this repo, so they are removed from xfails.

[no-jira]

* Remove unused typeMap

[no-jira]

* Add new xfails

[no-jira]

* Another p4c update

[no-jira]

* Adjust expected output in unit test

Also the constructor for the extern is added because otherwise
a different error is produced which is most likely a consequence
of this change: https://github.com/p4lang/p4c/pull/3686

[no-jira]

* Expect StructExpression as a parameter for MathUnit extern

As a consequence of this change:
https://github.com/p4lang/p4c/pull/3686
ListExpression which is a parameter of MathUnit extern constructor
is replaced by StructExpression in midend pass EliminateTuples.

This was causing reporting of the following error:

error: StructExpression is not a list expression

during CreateSaluInstruction.

[no-jira]

* Another p4c update

[no-jira]