add valid context paths to manifest only if the assembly succeeds (#3164)
Logging improvements 
* add valid paths to manifest only if the file generation succeeds. If 
for some reason we do not generate a file, do not store its path in the manifest.

P4VIS-834  #assign #start-work #fixed

* add support for generating log files even when the compiler fails.

Several changes to how we handle outputs on error:
- the compiler will generate a empty context.json because all
  the tools depend on it being there. This allows us to generate
  all the summary logs.
- Even if the compilation failed, but the assembler is invoked and
  can successfully do a bit of work, it will create a context.json
  that overrides the one generated by the compiler.
- Changed the behavior of the driver to not exit on errors. This
  allows all the other passes to run, including generating summary
  logs and archives (if requested)

* Improvements

- ensure that the files that we publish in the manifest exist
- ensure that the manifest is written only once (serialize closes the stream)
- properly setup the architecture configuration
- generate summary logging when the compiler fails and we do not get
  to run the assembler
- fix the issue with the rc == None (needs p4c refpoint update)
- when PHV fails, print PHV summary in the log file, not just the console
  TODO: how do we represent the non-fitting in the pa.results.log?
- pretty print the errors in p4c-build-logs