fixes compilation failure for gcc-4.9 (#1575)
* fixes compilation failure for gcc-4.9

gcc 4.9 requires an explicit constructor object for basic_istream.

* and handling of boost::optional which is also somehow busted with gcc4.9

This commit avoids the following error:
```
CMakeFiles/gtestp4c.dir/__/extensions/bf-p4c/test/gtest/phv_crush.cpp.o:phv_crush.cpp:function void testing_internal::DefaultPrintNonContainerTo<boost::optional<std::list<PHV::SuperCluster*, std::allocator<PHV::SuperCluster*> > > >(boost::optional<std::list<PHV::SuperCluster*, std::allocator<PHV::SuperCluster*> > > const&, std::ostream*): error: undefined reference to 'std::basic_ostream<char, std::char_traits<char> >& boost::operator<< <char, std::char_traits<char>, std::list<PHV::SuperCluster*, std::allocator<PHV::SuperCluster*> > >(std::basic_ostream<char, std::char_traits<char> >&, boost::optional<std::list<PHV::SuperCluster*, std::allocator<PHV::SuperCluster*> > > const&)'
```

Not clear what needs to happen here. Did boost forget to define
`operator <<` for `boost::none`?